version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "db"
      - "minio"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/AlgoMathDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    networks:
      - app-network

  db:
    image: postgres
    environment:
      POSTGRES_DB: AlgoMathDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  minio:
    image: bitnami/minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
  minio-data:
