spring:
  datasource:
    url: jdbc:postgresql://localhost/AlgoMathDB
    username: postgres
    password: 123
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  mail:
    protocol: smtps
    host: smtp.yandex.ru
    port: 465
    username: Fizi.1979@yandex.ru
    password: upgjammrkzmkxdxf

AlgoMath:
  app:
    jwtSecret: AlgoMath
    jwtCookieName: AlgoMath
    jwtExpirationMs: 86400000
    jwtRefreshCookieName: algomath-jwt-refresh
    jwtRefreshExpirationMs: 180000

minio:
  bucket:
    name: algomath
  access:
    key: minioadmin
    secret: minioadmin
  url: http://127.0.0.1:9000


#For TEST
#AlgoMath.app.jwtExpirationMs= 60000
