version: "3"

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "AlgoMathDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
